/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as EmployersIndexRouteImport } from './routes/employers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as EmployersEmployerIdRouteImport } from './routes/employers.$employerId'
import { Route as AdminSubscribersIndexRouteImport } from './routes/admin.subscribers.index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin.jobs.index'
import { Route as AdminEmployersIndexRouteImport } from './routes/admin.employers.index'
import { Route as AdminJobsNewRouteImport } from './routes/admin.jobs.new'
import { Route as AdminEmployersNewRouteImport } from './routes/admin.employers.new'
import { Route as AdminJobsJobIdEditRouteImport } from './routes/admin.jobs.$jobId.edit'
import { Route as AdminEmployersEmployerIdEditRouteImport } from './routes/admin.employers.$employerId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersIndexRoute = EmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersEmployerIdRoute = EmployersEmployerIdRouteImport.update({
  id: '/employers/$employerId',
  path: '/employers/$employerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersIndexRoute = AdminSubscribersIndexRouteImport.update({
  id: '/subscribers/',
  path: '/subscribers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersIndexRoute = AdminEmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersNewRoute = AdminEmployersNewRouteImport.update({
  id: '/employers/new',
  path: '/employers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsJobIdEditRoute = AdminJobsJobIdEditRouteImport.update({
  id: '/jobs/$jobId/edit',
  path: '/jobs/$jobId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersEmployerIdEditRoute =
  AdminEmployersEmployerIdEditRouteImport.update({
    id: '/employers/$employerId/edit',
    path: '/employers/$employerId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/employers/$employerId': typeof EmployersEmployerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/employers/new': typeof AdminEmployersNewRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/employers/': typeof AdminEmployersIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/subscribers/': typeof AdminSubscribersIndexRoute
  '/admin/employers/$employerId/edit': typeof AdminEmployersEmployerIdEditRoute
  '/admin/jobs/$jobId/edit': typeof AdminJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/employers/$employerId': typeof EmployersEmployerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/employers': typeof EmployersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/employers/new': typeof AdminEmployersNewRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/employers': typeof AdminEmployersIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/subscribers': typeof AdminSubscribersIndexRoute
  '/admin/employers/$employerId/edit': typeof AdminEmployersEmployerIdEditRoute
  '/admin/jobs/$jobId/edit': typeof AdminJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/employers/$employerId': typeof EmployersEmployerIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/employers/new': typeof AdminEmployersNewRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/employers/': typeof AdminEmployersIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/subscribers/': typeof AdminSubscribersIndexRoute
  '/admin/employers/$employerId/edit': typeof AdminEmployersEmployerIdEditRoute
  '/admin/jobs/$jobId/edit': typeof AdminJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/employers/$employerId'
    | '/jobs/$jobId'
    | '/admin/'
    | '/employers/'
    | '/jobs/'
    | '/admin/employers/new'
    | '/admin/jobs/new'
    | '/admin/employers/'
    | '/admin/jobs/'
    | '/admin/subscribers/'
    | '/admin/employers/$employerId/edit'
    | '/admin/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/employers/$employerId'
    | '/jobs/$jobId'
    | '/admin'
    | '/employers'
    | '/jobs'
    | '/admin/employers/new'
    | '/admin/jobs/new'
    | '/admin/employers'
    | '/admin/jobs'
    | '/admin/subscribers'
    | '/admin/employers/$employerId/edit'
    | '/admin/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/employers/$employerId'
    | '/jobs/$jobId'
    | '/admin/'
    | '/employers/'
    | '/jobs/'
    | '/admin/employers/new'
    | '/admin/jobs/new'
    | '/admin/employers/'
    | '/admin/jobs/'
    | '/admin/subscribers/'
    | '/admin/employers/$employerId/edit'
    | '/admin/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EmployersEmployerIdRoute: typeof EmployersEmployerIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  EmployersIndexRoute: typeof EmployersIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/': {
      id: '/employers/'
      path: '/employers'
      fullPath: '/employers/'
      preLoaderRoute: typeof EmployersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/$employerId': {
      id: '/employers/$employerId'
      path: '/employers/$employerId'
      fullPath: '/employers/$employerId'
      preLoaderRoute: typeof EmployersEmployerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers/': {
      id: '/admin/subscribers/'
      path: '/subscribers'
      fullPath: '/admin/subscribers/'
      preLoaderRoute: typeof AdminSubscribersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers/': {
      id: '/admin/employers/'
      path: '/employers'
      fullPath: '/admin/employers/'
      preLoaderRoute: typeof AdminEmployersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers/new': {
      id: '/admin/employers/new'
      path: '/employers/new'
      fullPath: '/admin/employers/new'
      preLoaderRoute: typeof AdminEmployersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$jobId/edit': {
      id: '/admin/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/admin/jobs/$jobId/edit'
      preLoaderRoute: typeof AdminJobsJobIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers/$employerId/edit': {
      id: '/admin/employers/$employerId/edit'
      path: '/employers/$employerId/edit'
      fullPath: '/admin/employers/$employerId/edit'
      preLoaderRoute: typeof AdminEmployersEmployerIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployersNewRoute: typeof AdminEmployersNewRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  AdminEmployersIndexRoute: typeof AdminEmployersIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminSubscribersIndexRoute: typeof AdminSubscribersIndexRoute
  AdminEmployersEmployerIdEditRoute: typeof AdminEmployersEmployerIdEditRoute
  AdminJobsJobIdEditRoute: typeof AdminJobsJobIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployersNewRoute: AdminEmployersNewRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  AdminEmployersIndexRoute: AdminEmployersIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminSubscribersIndexRoute: AdminSubscribersIndexRoute,
  AdminEmployersEmployerIdEditRoute: AdminEmployersEmployerIdEditRoute,
  AdminJobsJobIdEditRoute: AdminJobsJobIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EmployersEmployerIdRoute: EmployersEmployerIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  EmployersIndexRoute: EmployersIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
